// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAkRbUU_HY0k3KD48aFhYHt6mV8brcJE',
    appId: '1:683985736778:web:cf37bf406f2d36b797c2b3',
    messagingSenderId: '683985736778',
    projectId: 'movie-recommender-8d013',
    authDomain: 'movie-recommender-8d013.firebaseapp.com',
    storageBucket: 'movie-recommender-8d013.firebasestorage.app',
    measurementId: 'G-V0HHMV1FML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTmrmbaM2uGiCwWVClzV_sFkVUrn5VD-w',
    appId: '1:683985736778:android:8a062f2e40aaf62997c2b3',
    messagingSenderId: '683985736778',
    projectId: 'movie-recommender-8d013',
    storageBucket: 'movie-recommender-8d013.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerUZweU-OmBIjPMDSI6yCHisOnXn_C2g',
    appId: '1:683985736778:ios:1b3cf2b62cd7db9b97c2b3',
    messagingSenderId: '683985736778',
    projectId: 'movie-recommender-8d013',
    storageBucket: 'movie-recommender-8d013.firebasestorage.app',
    iosBundleId: 'com.example.movieRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAerUZweU-OmBIjPMDSI6yCHisOnXn_C2g',
    appId: '1:683985736778:ios:1b3cf2b62cd7db9b97c2b3',
    messagingSenderId: '683985736778',
    projectId: 'movie-recommender-8d013',
    storageBucket: 'movie-recommender-8d013.firebasestorage.app',
    iosBundleId: 'com.example.movieRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqAkRbUU_HY0k3KD48aFhYHt6mV8brcJE',
    appId: '1:683985736778:web:0940fd8bff613f8a97c2b3',
    messagingSenderId: '683985736778',
    projectId: 'movie-recommender-8d013',
    authDomain: 'movie-recommender-8d013.firebaseapp.com',
    storageBucket: 'movie-recommender-8d013.firebasestorage.app',
    measurementId: 'G-SCEYY5716K',
  );
}
